
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Content Author(s)|[Shannon Ellis]|
|Content Contributor(s)|[Candace Savonen] |
|Content Editor(s)/Reviewer(s) | [Candace Savonen], [Davon Person]|
|Content Director(s) | [Jeff Leek]|
|**Technical**||
|Course Publishing Engineer(s)|[Candace Savonen]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal])|[John Muschelli], [Candace Savonen], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)|[Shannon Ellis]|
|Figure Artist(s)|[Shannon Ellis]|
|**Funding**||
|Funder(s)| []|
|Funding Staff|[Ashley K.G. Johnson]|
|Support Staff Member| [Ashley K.G. Johnson], [Simone Sawyer]|
&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[Ashley K.G. Johnson]: https://www.linkedin.com/in/ashleykgjohnson/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Jeff Leek]: https://jtleek.com/
[John Muschelli]: https://johnmuschelli.com/
[Shannon Ellis]: https://www.shanellis.com/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
